### ISSUE TITLE
Question about testFixtures support

### ISSUE THREAD

**Issue by hendrikebbers** [gradlex-org/java-module-testing#4]
In the documentation of the plugin [test fixtures](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures) are not mentioned. We currently introduce test fixtures in a project to have test utilities without the need of having several additional modules. Do you have any plans how the plugin should take care about test fixtures? 

@jjohannes if you are interested we could do a (german) zoom call on that topic. I would like to get the setup as good as possible and willing to help here.

**Comment by jjohannes** [comment]
Right now, test fixtures are not specifically handled by this plugin. They shouldn't need to if you define them as separate module. For example, you can have a setup like this:


```
|-- integtest
|   `-- java
|       `-- module-info.java
|-- main
|   `-- java
|       `-- module-info.java
`-- testFixtures
    `-- java
        `-- module-info.java
```

Each sources set is it's own module. In this case `integtest` are blackbox tests. 

`testFixtures/java/module-info.java` may look like this:

```
open module org.my.lib.test.fixtures {
    requires org.my.lib; // This is the Module Name of the "main" Module
}
```

And then `integtest/java/module-info.java` may look something like this, requiring the test fixtures:

```
open module org.my.lib.integtest {
    requires org.my.lib;
    requires org.my.lib.test.fixtures;
    requires org.junit.jupiter.api;
}
```


If you somehow need to do something more "whitebox", it depends on what exactly you need to achieve. Maybe there is something that could be added to this plugin. For example, if the _test fixtures_ would need to be patched into the _main_ module in order to work. Although this would get ugly I think, because the test fixtures are (usually) also there to be used by other projects (modules). So I think I would avoid using test fixtures in combination with "whitebox" tests.

I am happy to have a chat next week. Please get in touch via mail - jendrik@onepiece.software

**Comment by hendrikebbers** [comment]
I'm in general with you. It becomes more problematically when you want to define unit tests as "whitebox" tests since this is how they were developed for a long time and a package split will end in endless refactoring based on package private usage for tests (common case that you can find in many projects). Based on that you can not do a Big Bang approach and switch unit tests to "blackbox" tests with real modules.


Let's assume you have the following structure

```
|-- main
|   `-- java
|       |-- com.sample.app
|       `-- module-info.java
|
|-- test
|   `-- java
|       `-- com.sample.app
|       
|-- integtest
|   `-- java
|       |-- com.sample.app.test.integrationtests
|       `-- module-info.java
|      
`-- testFixtures
    `-- java
        |-- com.sample.app.testfictures
        `-- module-info.java
```

In the given sample the `integtest` set can be executed as real blackbox tests. The `test` set is no Java module at all and has the same base package as the `main` set (based on the project history). Next to this the `test` set automatically depends on the `main` set and the `testFixtures` set. An easy option would be to run all tests on the classpath instead of the module path but that will create several pitfalls / problems like ignoring `provides`/`use` definition in java module definition. This is a problem that can not easily be solved since we have the following dependency tree:

test --> testFixtures --> main

Based on this we can not merge `test` & `main` as a module like the plugin can do it. Here we need a solution to merge all 3 🙈 But in general that should not be harder than merging 2 of them...

**Comment by jjohannes** [comment]
Thanks for clarifying your setup @hendrikebbers. What you describe makes sense.

If you are able to define at least the fixtures as a separate module, I think you can use this plugin as it is now. You can do something like this:

```
javaModuleTesting.whitebox(
   testing.suites.getByName<JvmTestSuite>("test") {
        useJUnitJupiter() // reconfigure to use JUnit5 (default is JUnit4)
    }
) {
    // Additional 'requires' and 'opens' used only for tests (this plugin adds the corresponding command line parameters for javac/java)
    requires.add("org.junit.jupiter.api")
    opensTo.add("org.junit.platform.commons")

    requires.add("com.sample.app.testfixtures") // also require our own test fixtures module
}
```

Note that the 'test-fixtures.jar' is already seen by the tests, because that's the default setup Gradle does when using the `test-fixtures` plugin. If we now run the unit test as (patched) module, we need to add the `requires` as well, which this plugin can do as shown above.

I think it makes sense to add this to the Readme this (which I will do).
