### ISSUE TITLE
Support classpath testing (not changing Gradle default setup for whitebox)

### ISSUE THREAD

**Issue by xenoterracide** [gradlex-org/java-module-testing#47]
So from what I read here. By default this overrides gradle's default test stuff. I don't actually want that, most of the time I want whitebox testing. The only reason I want blackbox testing is to ensure that the right packages are exported. It's not clear from the documentation whether I could add a jvm test suite with this that is just the addition of blackbox testing, and leaves the default alone.

**Comment by xenoterracide** [comment]
appears to be whitebox to me, this test wouldn't pass if `test` wasn't whitebox

https://github.com/xenoterracide/java-commons/blob/chore/publication/module/tools/src/test/java/com/xenoterracide/tools0/java/internal/DemoWhiteBoxTest.java

https://github.com/xenoterracide/java-commons/blob/chore/publication/module/tools/src/main/java/com/xenoterracide/tools0/java/internal/DemoWhiteBox.java

https://github.com/xenoterracide/java-commons/blob/chore/publication/module/tools/src/main/java/module-info.java

**Comment by xenoterracide** [comment]
yeah, it looks like this is a must feature for me because of #51 if I could just turn it off for test suites where I want to test package private things that'd be perfect, but it appears that it wants to take over all jvm test suites, so I can't even make another one with the module path not added in some way.

Guess my option is fork this plugin and dig around?

**Comment by jjohannes** [comment]
I think we might have a bit of misunderstanding about what "Whitebox" means here. Because the plugin does something to do "Whitebox" testing with modules (merging main and test Module). Which in the terminology used in this plugin is Whitebox Testing (on the Module Path).

If I understand it correctly, you are talking about running tests on the Classpath. Which is what Gradle is doing when you do not use this plugin and do not have a `module-info.java` for your tests.

I still think a really good setup would be to not test on the Classpath at all. But in practice, this is difficult to achieve with certain test frameworks and libraries that do e.g. mocking stuff and need access to more things than the Module System would allow.

Not sure if that is your use case, but in any case I think we can add an option to tell the plugin to not touch a "Test Suite" to do "classpath-based" testing. I think I would call it something like that:

```
javaModuleTesting.classspath(testing.suites["test"])
```

**Comment by xenoterracide** [comment]
I choose to slice my modules both vertically and horizontally, e.g `feature.model` and `feature.controller` to avoid layer specific code from leaking into another layer and features being preserved in isolation. Most of my code can be tested using blackbox tests with a module-info. Vampire (on slack gradle) says that even adding a module-info to gradle without using this will still leak (or allow hiding?) of resources. Something like 10-20% of my code needs to be whitebox-ed because I'm hiding something super specific in the module behind package/protected code. I use the Testing Trophy instead of the Testing Pyramid.

What I think I want to do is alway use `test` for blackbox testing, and then make a jvm test suite like `testWhiteBox` for whitebox testing. I just don't see the need to have non classpath code overhead if I always have a blackbox suite.

**Comment by xenoterracide** [comment]
any chance this will be seen anytime soon? was just going to go ahead and apply in my buildSrc and then I remembered this problem. Another reason this would be good is incremental progression towards a modular build.

**Comment by jjohannes** [comment]
I agree that this feature should be in the next release. I had some busy weeks. I'll try to get to this soon.
